import { Schema } from "mongoose";

/**
 * Embedded block schema. `_id: false` because blocks use their own
 * permanent `id` (a UUID generated by the frontend) — never a Mongo
 * ObjectId and never an array index.
 */
export const BlockSchema = new Schema(
  {
    id: { type: String, required: true },
    order: { type: Number, required: true },
    text: { type: String, default: "" },
    provider: { type: String, enum: ["elevenlabs", "cartesia"], required: true },
    voiceId: { type: String, required: true },
    settings: {
      model: String,
      language: String,
      speed: Number,
      pitch: Number,
      volume: Number,
    },
    status: {
      type: String,
      enum: ["idle", "pending", "generating", "reused", "generated", "failed"],
      default: "idle",
    },
    audioArtifactId: String,
    audioUrl: String,
    hash: String,
    error: String,
  },
  { _id: false }
);
